server:
  port: 9001
spring:
  application:
    name: kong
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password123
    username: user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

message:
  topic:
    name: kong
greeting:
  topic:
    name: greeting
filtered:
  topic:
    name: filtered
partitioned:
  topic:
    name: partitioned
multi:
  type:
    topic:
      name: multitype
monitor:
  kafka:
    bootstrap:
      config: localhost:9092
    consumer:
      groupid: kong
  topic:
    name: kong
  producer:
    simulate: true
  consumer:
    simulate: true